version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sql-agent-db
    environment:
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_password
      POSTGRES_DB: property_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user -d property_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SQL Agent Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql-agent-app
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql://agent_user:agent_password@postgres:5432/property_db
      API_HOST: 0.0.0.0
      API_PORT: 8000
      API_RELOAD: "false"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
